#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Write a short tagline for your app.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Yashvardhan Mulki                                
your_link                                 : https://yashmulki.me                     
your_city                                 : Oakville, Canada                                
email_address                             : quantumpointdev@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : ysmulki
github_username                           : yashmulki
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : News
    description                           : Get a curated feed of this week's top political news from trusted sources
    fontawesome_icon_name                 : newspaper
    
  - title                                 : Polls
    description                           : Keep track of how all parties are doing with polling updates
    fontawesome_icon_name                 : bar-chart

  - title                                 : Candidates
    description                           : View and connect with candidates in the 2019 Federal Election
    fontawesome_icon_name                 : user-circle

  - title                                 : Election Information
    description                           : View the date for the election and add it to your calendar so you won't forget to vote
    fontawesome_icon_name                 : info-circle

  - title                                 : Representatives
    description                           : View representatives at all levels of government and easily get in touch with them to voice your concerns
    fontawesome_icon_name                 : id-card
  
  - title                                 : Voting Record
    description                           : See what your MP is doing in Ottawa with easy access to their recent votes in Parliament
    fontawesome_icon_name                 : check-circle

  - title                                 : Party Platforms
    description                           : Explore the options and find your party
    fontawesome_icon_name                 : file-text

  - title                                 : Organize
    description                           : Remind your contacts to vote in the election with built in messaging tools
    fontawesome_icon_name                 : commenting

  - title                                 : Support
    description                           : Contact quantumpointdev@gmail.com for help with any issues
    fontawesome_icon_name                 : question-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#e03c3c"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#e04f3c"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#e04f3c"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#e04f3c"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
